FROM node:lts

# Install all dependencies required for compiling quickjs
RUN apt-get update && apt-get install -y build-essential libzmq3-dev libffi6 libffi-dev

VOLUME /usr/src

WORKDIR /usr/src

CMD ["bash"]