name: Deploy Docs

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        npm install
        npm run api-docs
    - name: Deploy
      run: |
         git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
         npm run deploy-api-docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
